name: APIService

on:
  push:
    branches: [ "main" ]
jobs:
  tests:
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_USER: mysql
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: main
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.21.2
        with:
          php-version: 8.2
      - run: cp .env.example .env
      - run: composer install -n --prefer-dist
      - run: php artisan key:generate
      - run: php artisan test || true
